#!/usr/bin/env python3
"""Generate docs/api/*.md - one markdown file per API module, for the frontend track.

Reads the live FastAPI OpenAPI schema and emits readable markdown: endpoints,
parameters, request and response shapes, error codes, and worked examples.

    python scripts/generate_api_docs.py                    # import the app
    python scripts/generate_api_docs.py --url http://localhost:8000/openapi.json

Run after any endpoint change (CLAUDE.md §2.5). Never hand-edit the output -
edit the Pydantic models and the endpoint docstrings, then regenerate.

Docstrings become prose in the generated doc, so write them for the frontend track:
what the endpoint is for, not what the code does.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "api"
METHODS = ("get", "post", "put", "patch", "delete")


def load_schema(url: str | None) -> dict[str, Any]:
    if url:
        import urllib.request
        with urllib.request.urlopen(url) as r:
            return json.load(r)
    sys.path.insert(0, str(ROOT))
    try:
        from api.main import app  # type: ignore
    except ImportError:
        print("Could not import api.main. Pass --url, or run once api/ exists.")
        raise SystemExit(1)
    return app.openapi()


def resolve(ref: str, schema: dict) -> dict:
    node: Any = schema
    for part in ref.lstrip("#/").split("/"):
        node = node.get(part, {})
    return node


def type_of(prop: dict, schema: dict) -> str:
    if "$ref" in prop:
        return prop["$ref"].split("/")[-1]
    if "anyOf" in prop:
        # escaped: this text lands in a table cell, where a bare | starts a new column
        return " \\| ".join(type_of(p, schema) for p in prop["anyOf"])
    t = prop.get("type", "any")
    if t == "array":
        return f"{type_of(prop.get('items', {}), schema)}[]"
    fmt = prop.get("format")
    if fmt in ("date-time", "date", "uuid"):
        return fmt
    if prop.get("enum"):
        return " \\| ".join(f"`{v}`" for v in prop["enum"])
    return t


def _prop_refs(prop: dict) -> list[str]:
    """Every component a property points at: directly, through `items`, or
    through the arms of anyOf, oneOf and allOf."""
    out: list[str] = []
    candidates = [prop, prop.get("items", {}),
                  *prop.get("anyOf", []), *prop.get("oneOf", []), *prop.get("allOf", [])]
    for cand in candidates:
        if not isinstance(cand, dict):
            continue
        if cand.get("$ref"):
            out.append(str(cand["$ref"]).split("/")[-1])
        items = cand.get("items", {})
        if isinstance(items, dict) and items.get("$ref"):
            out.append(str(items["$ref"]).split("/")[-1])
    return out


def render_model(name: str, schema: dict, depth: int = 0) -> list[str]:
    """Render a component schema as a markdown table."""
    comp = schema.get("components", {}).get("schemas", {}).get(name)
    if not comp or depth > 2:
        return []
    props = comp.get("properties", {})
    if not props:
        return []
    required = set(comp.get("required", []))
    out = [f"**`{name}`**", "", "| Field | Type | Required | Notes |", "|---|---|---|---|"]
    for field, prop in props.items():
        req = "yes" if field in required else ""
        note = prop.get("description", "")
        if "default" in prop:
            note = (note + f" Default `{prop['default']}`.").strip()
        out.append(f"| `{field}` | {type_of(prop, schema)} | {req} | {note} |")
    out.append("")
    return out


def module_of(path: str, tags: list[str]) -> str:
    if tags:
        return tags[0].lower().replace(" ", "-")
    parts = [p for p in path.split("/") if p and not p.startswith("{")]
    for p in parts:
        if p not in ("api", "v1", "public"):
            return p
    return "misc"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--url")
    args = ap.parse_args()

    schema = load_schema(args.url)
    by_module: dict[str, list[tuple[str, str, dict]]] = defaultdict(list)
    for path, item in schema.get("paths", {}).items():
        for method in METHODS:
            if op := item.get(method):
                by_module[module_of(path, op.get("tags", []))].append((method, path, op))

    OUT.mkdir(parents=True, exist_ok=True)
    today = dt.date.today().isoformat()
    written: list[tuple[str, int]] = []

    for module, ops in sorted(by_module.items()):
        used_models: set[str] = set()
        lines = [
            f"# API — {module.replace('-', ' ').title()}",
            "",
            f"> Generated by `scripts/generate_api_docs.py` on {today}. **Never hand-edit.**",
            "> Base URL: `/api/v1`. Requests need `Authorization: Bearer <access_token>`",
            "> **except** the four endpoints that cannot carry one - `/auth/login`,",
            "> `/auth/otp/verify`, `/auth/refresh` and `/auth/logout` - and anything under",
            "> `/public`.",
            "",
            "Conventions for every endpoint in this file:",
            "",
            "- Success: `{ \"data\": ... }`",
            "- Failure: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }`. Switch on `code`;",
            "  `message` is for a human and may be reworded without notice",
            "- A `422` is schema validation and uses the same envelope, with a `fields`",
            "  map from field path to reason so a form can mark the offending input",
            "- Money is a **decimal string**, never a number: `\"1234.56\"`",
            "- Timestamps are ISO-8601 UTC; render in IST",
            "- Every POST/PATCH takes `Idempotency-Key`, and replaying returns the first",
            "  response. **The `/auth` mutations are the exception** and take none: login and",
            "  OTP verify are replay-safe through their own ninety-second windows, and refresh",
            "  is rotation, where a repeat is the case the grace window already handles",
            "- Collections accept `page`, `limit`, `sort`, `q` plus the filters listed",
            "- Rows are already scoped by the caller's permissions. An empty list means",
            "  nothing in scope, **not** an error. A `403` means the action is not permitted at all.",
            "",
            "---",
            "",
        ]

        for method, path, op in sorted(ops, key=lambda x: (x[1], x[0])):
            summary = op.get("summary") or f"{method.upper()} {path}"
            lines += [f"## `{method.upper()} {path}`", "", f"**{summary}**", ""]

            if desc := (op.get("description") or "").strip():
                lines += [desc, ""]

            params = op.get("parameters", [])
            if params:
                lines += ["**Parameters**", "", "| Name | In | Type | Required | Notes |", "|---|---|---|---|---|"]
                for p in params:
                    lines.append(
                        f"| `{p['name']}` | {p.get('in','')} | {type_of(p.get('schema', {}), schema)} "
                        f"| {'yes' if p.get('required') else ''} | {p.get('description','')} |"
                    )
                lines.append("")

            body = op.get("requestBody", {}).get("content", {}).get("application/json", {}).get("schema", {})
            if ref := body.get("$ref"):
                name = ref.split("/")[-1]
                used_models.add(name)
                lines += ["**Request body**", "", *render_model(name, schema)]

            lines += ["**Responses**", "", "| Status | Body | Meaning |", "|---|---|---|"]
            for code, resp in sorted(op.get("responses", {}).items()):
                content = resp.get("content", {}).get("application/json", {}).get("schema", {})
                ref = content.get("$ref") or content.get("items", {}).get("$ref", "")
                model = ref.split("/")[-1] if ref else "-"
                if model != "-":
                    used_models.add(model)
                lines.append(f"| `{code}` | {f'`{model}`' if model != '-' else '-'} | {resp.get('description','')} |")
            lines += ["", "---", ""]

        # A model nested inside another (an envelope's `data`, a list's items) is
        # part of the contract too: walk the references until nothing new appears.
        # Without this the OTP request's response model was never expanded, and the
        # one field FS-007 added to the API was in no generated doc.
        schemas = schema.get("components", {}).get("schemas", {})
        frontier = list(used_models)
        while frontier:
            for prop in schemas.get(frontier.pop(), {}).get("properties", {}).values():
                for ref in _prop_refs(prop):
                    if ref not in used_models:
                        used_models.add(ref)
                        frontier.append(ref)

        if used_models:
            lines += ["## Models", ""]
            for name in sorted(used_models):
                lines += render_model(name, schema)

        f = OUT / f"{module}.md"
        f.write_text("\n".join(lines), encoding="utf-8")
        written.append((module, len(ops)))

    index = [
        "# API Documentation",
        "",
        f"> Generated by `scripts/generate_api_docs.py` on {today}. **Never hand-edit.**",
        "",
        "One file per module. Shared with the frontend track as the frontend contract; regenerated after",
        "any endpoint change, so it is always current rather than a snapshot.",
        "",
        "| Module | Endpoints | Doc |",
        "|---|---|---|",
    ]
    for module, n in sorted(written):
        index.append(f"| {module.replace('-', ' ').title()} | {n} | [`{module}.md`]({module}.md) |")
    index += [
        "",
        "---",
        "",
        "## Conventions",
        "",
        "| | |",
        "|---|---|",
        "| Base URL | `/api/v1` |",
        "| Auth | `Authorization: Bearer <access_token>`, except the pre-auth "
        "`/auth` endpoints and `/public/*` |",
        "| Success | `{ \"data\": ... }` |",
        "| Error | `{ \"error\": { \"code\", \"message\", \"fields\"? } }` — the same envelope on 422, with `fields` mapping field path to reason |",
        "| Money | decimal **string** — `\"1234.56\"` |",
        "| Time | ISO-8601 UTC, rendered IST |",
        "| Idempotency | `Idempotency-Key` on every POST/PATCH, except the `/auth` mutations |",
        "| Pagination | by cursor, not page number: `limit`, then the previous page's "
        "`meta.next_cursor` as `cursor`; absent on the last page. `include_total=true` "
        "adds `meta.total` (capped, see `meta.total_capped`) where a list offers it |",
        "",
        "**Empty list versus 403.** Rows are scoped by permission in the database. An empty",
        "collection means nothing is in the caller's scope; `403` means the action itself is",
        "not permitted. These are different and the UI should treat them differently.",
        "",
        "## Changes",
        "",
        "Additive changes (a new endpoint, a new optional field) need no ceremony.",
        "**Breaking changes require agreement from both engineers** — they invalidate",
        "whatever the frontend track has built against the previous shape (ADR-028).",
        "",
    ]
    (OUT / "README.md").write_text("\n".join(index), encoding="utf-8")

    total = sum(n for _, n in written)
    print(f"wrote {len(written)} module docs + index to docs/api/ ({total} endpoints)")


if __name__ == "__main__":
    main()
