"""001 foundation: extensions, audit_log, the generic audit trigger, updated_at

FS-001 section 5. Hand-written, not autogenerated: alembic emits none of the
parts that matter here (CLAUDE.md 4.3).

Two things in this file are ordering decisions rather than preferences, and both
are argued in FS-001 section 5:

  * `audit_log` is created here even though `Proposed-Schema.md` section 18 lists
    it in no migration at all. It is defined in section 16 and then never built.
    The trigger below writes into it, and attaching that trigger with no table
    underneath fails on the first INSERT rather than at migration time.
  * `audit_row()` is LANGUAGE plpgsql, not sql. It calls `app_current_user_id()`,
    which migration 003 creates. `check_function_bodies` is on, so a `sql` body
    is validated at CREATE FUNCTION time and would fail here exactly as round 1's
    B-1 established for the six RBAC helpers. plpgsql defers its body to first
    execution, and nothing executes it before 003 has run.

Revision ID: 001_foundation
Revises:
Created: during development
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "001_foundation"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # Proposed-Schema.md section 15. Exempt from the common columns in section 1.2:
    # it is immutable and never soft-deleted.
    #
    # actor_id carries no foreign key. It is populated from app_current_user_id(),
    # created at the end of 003, so an FK would make 001 depend on 003 - and an
    # audit row has to outlive the deletion of the actor it names regardless.
    op.execute(
        """
        CREATE TABLE audit_log (
            id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
            actor_id    uuid,
            action      text        NOT NULL,
            table_name  text        NOT NULL,
            row_id      uuid,
            old_jsonb   jsonb,
            new_jsonb   jsonb,
            at          timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_audit_log_action
                CHECK (action IN ('INSERT', 'UPDATE', 'DELETE'))
        )
        """
    )
    # Proposed-Schema.md section 17. The read is always "what happened to this row".
    op.execute(
        "CREATE INDEX ix_audit_log_table_row_at ON audit_log (table_name, row_id, at DESC)"
    )

    # One generic trigger writes every audit row, rather than application code.
    # Application code can be bypassed by a direct SQL fix; a trigger cannot
    # (Proposed-Schema.md section 15).
    #
    # SECURITY DEFINER because migration 017 will put RLS on audit_log and the
    # writing role will not hold INSERT on it. The function takes no caller input:
    # every value comes from the trigger context or from the row being changed, so
    # there is nothing here for a caller to steer.
    #
    # password_hash is stripped from both payloads. The trigger writes the whole
    # row as old_jsonb/new_jsonb, so attached unmodified to app_user it would copy
    # every Argon2 hash into a table with no delete path and a wider read audience
    # than app_user itself - undoing FS-001 section 5.1's containment argument,
    # where the hash leaves the database "only that one column, for one email,
    # through one function".
    #
    # row_id reads the row's own id. Every table this is attached to has one; a
    # junction table without one would silently log NULL, which is why
    # user_territory carries an id of its own (FS-001 section 5).
    op.execute(
        """
        CREATE FUNCTION audit_row() RETURNS trigger
        LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
        DECLARE
            v_old jsonb;
            v_new jsonb;
        BEGIN
            IF TG_OP <> 'INSERT' THEN
                v_old := to_jsonb(OLD);
            END IF;
            IF TG_OP <> 'DELETE' THEN
                v_new := to_jsonb(NEW);
            END IF;

            IF TG_TABLE_NAME = 'app_user' THEN
                v_old := v_old - 'password_hash';
                v_new := v_new - 'password_hash';
            END IF;

            INSERT INTO audit_log (actor_id, action, table_name, row_id,
                                   old_jsonb, new_jsonb)
            VALUES (app_current_user_id(), TG_OP, TG_TABLE_NAME,
                    coalesce((v_new ->> 'id')::uuid, (v_old ->> 'id')::uuid),
                    v_old, v_new);

            RETURN NULL;  -- AFTER trigger; the return value is discarded
        END $fn$
        """
    )

    # Common column, common trigger. updated_by is set by the application, because
    # only the application knows whether a write is a user action or a job.
    op.execute(
        """
        CREATE FUNCTION set_updated_at() RETURNS trigger
        LANGUAGE plpgsql AS $fn$
        BEGIN
            NEW.updated_at := now();
            RETURN NEW;
        END $fn$
        """
    )


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    op.execute("DROP FUNCTION IF EXISTS audit_row()")
    op.execute("DROP TABLE IF EXISTS audit_log")
    # The extensions are deliberately left in place. They are cluster-visible,
    # cheap, and dropping pgcrypto would break anything else in the database that
    # reached for gen_random_uuid().
